name: Build and Push

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: Build and push to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:1.0.0
